# Generated by Django 5.2.1 on 2025-05-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheshop', '0002_remove_order_products_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_messenger',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
