# Generated by Django 5.0.4 on 2025-06-23 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheshop', '0004_alter_order_preferred_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Футболка', 'Футболка'), ('Рубашка', 'Рубашка'), ('Брюки', 'Брюки'), ('Джинсы', 'Джинсы'), ('Платье', 'Платье'), ('Костюм', 'Костюм'), ('Юбка', 'Юбка'), ('Свитер', 'Свитер'), ('Свитшот', 'Свитшот'), ('Худи', 'Худи'), ('Лонгслив', 'Лонгслив'), ('Шорты', 'Шорты'), ('Бермуды', 'Бермуды'), ('Куртка', 'Куртка'), ('Шапка', 'Шапка'), ('Кепка', 'Кепка')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductNoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_size_info', to='clotheshop.product')),
            ],
        ),
    ]
