# Generated by Django 5.0.4 on 2025-06-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheshop', '0005_alter_message_phone_alter_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Без Размера', 'Без Размера')], max_length=15),
        ),
        migrations.DeleteModel(
            name='ProductNoSize',
        ),
    ]
